#!/usr/bin/env bash
#
# install standard packages.

set -e

# install homebrew and standard packages
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install zsh coreutils git hub n yarn --without-node
brew cask install caffeine alfred sizeup atom iterm2

# install latest version of node
n latest

# make zsh the default shell
sudo bash -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
chsh -s /usr/local/bin/zsh
